In [5]:
import numpy as np
import pandas as pd

**Creating DataFrame**

In [6]:
data={
    'Name' : ['Alok','Rohan','Mohit','Kaushal'],
    'Age' : [24,20,19,21],
    'City' : ['New York','Paris','Berlin','London'],
    'Salary' : [65000,70000,62000,85000]
}
df=pd.DataFrame(data)

In [7]:
df

      Name  Age      City  Salary
0     Alok   24  New York   65000
1    Rohan   20     Paris   70000
2    Mohit   19    Berlin   62000
3  Kaushal   21    London   85000

In [8]:
data_list=[
    ['Alok',24,'Varanasi',65000],
    ['Mohit',22,'New York',62000],
    ['Rachit',23,'Berlin',50000],
    ['Rohan',19,'London',63000]
]
df2=pd.DataFrame(data_list)
df2

        0   1         2      3
0    Alok  24  Varanasi  65000
1   Mohit  22  New York  62000
2  Rachit  23    Berlin  50000
3   Rohan  19    London  63000

In [9]:
columns=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

     Name  Age      City  Salary
0    Alok   24  Varanasi   65000
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000
3   Rohan   19    London   63000

**Selection and Indexing of Columns**

In [10]:
df2['Name']

0      Alok
1     Mohit
2    Rachit
3     Rohan
Name: Name, dtype: object

In [11]:
df2[['Age','City']]

   Age      City
0   24  Varanasi
1   22  New York
2   23    Berlin
3   19    London

In [12]:
df2['Designation']=['Engineer','Doctor','Teacher','Lawyer']
df2

     Name  Age      City  Salary Designation
0    Alok   24  Varanasi   65000    Engineer
1   Mohit   22  New York   62000      Doctor
2  Rachit   23    Berlin   50000     Teacher
3   Rohan   19    London   63000      Lawyer

**Removing Columns**

In [13]:
df2.drop('Designation',axis=1)

     Name  Age      City  Salary
0    Alok   24  Varanasi   65000
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000
3   Rohan   19    London   63000

In [14]:
df2

     Name  Age      City  Salary Designation
0    Alok   24  Varanasi   65000    Engineer
1   Mohit   22  New York   62000      Doctor
2  Rachit   23    Berlin   50000     Teacher
3   Rohan   19    London   63000      Lawyer

In [15]:
df2.drop('Designation',axis=1,inplace=True)

In [16]:
df2

     Name  Age      City  Salary
0    Alok   24  Varanasi   65000
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000
3   Rohan   19    London   63000

In [17]:
df2.drop(['Age','Salary'],axis=1)

     Name      City
0    Alok  Varanasi
1   Mohit  New York
2  Rachit    Berlin
3   Rohan    London

In [18]:
df2

     Name  Age      City  Salary
0    Alok   24  Varanasi   65000
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000
3   Rohan   19    London   63000

In [19]:
df2.drop(0,axis=0)

     Name  Age      City  Salary
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000
3   Rohan   19    London   63000

**Selecting Rows**

In [20]:
df2.loc[0]

Name          Alok
Age             24
City      Varanasi
Salary       65000
Name: 0, dtype: object

In [22]:
df2.loc[[0,1]]

    Name  Age      City  Salary
0   Alok   24  Varanasi   65000
1  Mohit   22  New York   62000

In [23]:
df2.iloc[3]

Name       Rohan
Age           19
City      London
Salary     63000
Name: 3, dtype: object

**Selecting subsets of Rows and Columns**

In [24]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  Varanasi   65000
1  New York   62000

In [25]:
df2.loc[[2,3]][['Name','Age']]

     Name  Age
2  Rachit   23
3   Rohan   19

**Conditional Selection**

In [27]:
#I only want to see those people whose age is above 20
df2[df2['Age']>20]

     Name  Age      City  Salary
0    Alok   24  Varanasi   65000
1   Mohit   22  New York   62000
2  Rachit   23    Berlin   50000

In [28]:
df2[(df2['Age']>20) & (df2['City']=='Berlin')]

     Name  Age    City  Salary
2  Rachit   23  Berlin   50000